import { Proposal } from "./types"

export const DEMO_PROPOSALS: Proposal[] = [
  {
    id: "demo-1",
    user_id: "demo",
    public_token: "demo-token-1",
    title: "Website Redesign Project",
    client_name: "Acme Corp",
    client_email: "sarah@acme.com",
    status: "accepted",
    cover_tagline: "Modern, fast, and conversion-focused",
    intro: "We're excited to partner with Acme Corp on this website redesign initiative.",
    scope: "Full redesign of the marketing website including 10 pages, new design system, and CMS integration.",
    deliverables: "- New design mockups\n- Responsive website\n- CMS setup\n- 30 days support",
    timeline: "6 weeks from kickoff",
    terms: "50% upfront, 50% on delivery. Net 30 payment terms.",
    total_amount: 12500,
    currency: "USD",
    valid_until: "2026-04-30",
    view_count: 5,
    first_viewed_at: "2026-03-15T10:00:00Z",
    accepted_at: "2026-03-16T14:30:00Z",
    accepted_by_name: "Sarah Johnson",
    created_at: "2026-03-14T09:00:00Z",
    updated_at: "2026-03-16T14:30:00Z",
    proposal_items: [
      { id: "item-1", proposal_id: "demo-1", sort_order: 0, name: "UX Research & Strategy", description: "User interviews, competitive analysis, sitemap", quantity: 1, unit_price: 2500, total: 2500 },
      { id: "item-2", proposal_id: "demo-1", sort_order: 1, name: "UI Design", description: "10 page designs + design system", quantity: 1, unit_price: 4500, total: 4500 },
      { id: "item-3", proposal_id: "demo-1", sort_order: 2, name: "Development", description: "Next.js implementation + CMS", quantity: 1, unit_price: 5000, total: 5000 },
      { id: "item-4", proposal_id: "demo-1", sort_order: 3, name: "Support & QA", description: "30 days post-launch support", quantity: 1, unit_price: 500, total: 500 },
    ]
  },
  {
    id: "demo-2",
    user_id: "demo",
    public_token: "demo-token-2",
    title: "Brand Identity Package",
    client_name: "TechStart Inc",
    client_email: "mike@techstart.io",
    status: "viewed",
    cover_tagline: "A brand that stands out",
    intro: "TechStart needs a bold identity that communicates innovation and trust.",
    scope: "Logo design, color palette, typography, brand guidelines, and business card design.",
    deliverables: "- 3 logo concepts\n- Brand guidelines PDF\n- Business card design\n- Social media kit",
    timeline: "3 weeks",
    terms: "Net 15. Full payment required before final file delivery.",
    total_amount: 4800,
    currency: "USD",
    valid_until: "2026-04-15",
    view_count: 3,
    first_viewed_at: "2026-03-27T16:20:00Z",
    created_at: "2026-03-25T11:00:00Z",
    updated_at: "2026-03-27T16:20:00Z",
    proposal_items: [
      { id: "item-5", proposal_id: "demo-2", sort_order: 0, name: "Logo Design", description: "3 concepts, 2 revision rounds", quantity: 1, unit_price: 2000, total: 2000 },
      { id: "item-6", proposal_id: "demo-2", sort_order: 1, name: "Brand Guidelines", description: "Comprehensive brand guidelines document", quantity: 1, unit_price: 1500, total: 1500 },
      { id: "item-7", proposal_id: "demo-2", sort_order: 2, name: "Collateral Design", description: "Business cards + social media kit", quantity: 1, unit_price: 1300, total: 1300 },
    ]
  },
  {
    id: "demo-3",
    user_id: "demo",
    public_token: "demo-token-3",
    title: "SEO & Content Strategy",
    client_name: "GreenLeaf Co",
    client_email: "hello@greenleaf.com",
    status: "sent",
    cover_tagline: "Rank higher, grow faster",
    intro: "A comprehensive SEO strategy to help GreenLeaf dominate search rankings.",
    scope: "Technical SEO audit, keyword research, content calendar, and 3-month execution plan.",
    deliverables: "- Technical SEO audit report\n- Keyword strategy document\n- 3-month content calendar\n- Monthly reporting",
    timeline: "Ongoing — 3 month engagement",
    terms: "Monthly retainer, billed on the 1st.",
    total_amount: 6000,
    currency: "USD",
    valid_until: "2026-04-20",
    view_count: 0,
    created_at: "2026-03-28T08:00:00Z",
    updated_at: "2026-03-28T08:00:00Z",
    proposal_items: [
      { id: "item-8", proposal_id: "demo-3", sort_order: 0, name: "SEO Audit", description: "Technical audit + competitor analysis", quantity: 1, unit_price: 1500, total: 1500 },
      { id: "item-9", proposal_id: "demo-3", sort_order: 1, name: "Monthly Retainer", description: "Content creation, link building, reporting", quantity: 3, unit_price: 1500, total: 4500 },
    ]
  },
  {
    id: "demo-4",
    user_id: "demo",
    public_token: "demo-token-4",
    title: "Mobile App MVP",
    client_name: "FitTrack",
    client_email: "ceo@fittrack.app",
    status: "draft",
    cover_tagline: "From idea to App Store in 12 weeks",
    intro: "FitTrack's fitness tracking MVP built for iOS and Android.",
    scope: "React Native app with user auth, workout tracking, progress charts, and push notifications.",
    deliverables: "- iOS + Android app\n- Backend API\n- Admin dashboard\n- App Store submission",
    timeline: "12 weeks",
    terms: "33% upfront, 33% at midpoint, 34% at delivery.",
    total_amount: 28000,
    currency: "USD",
    view_count: 0,
    created_at: "2026-03-29T07:00:00Z",
    updated_at: "2026-03-29T07:00:00Z",
    proposal_items: [
      { id: "item-10", proposal_id: "demo-4", sort_order: 0, name: "Product Design", description: "UX/UI for all screens", quantity: 1, unit_price: 6000, total: 6000 },
      { id: "item-11", proposal_id: "demo-4", sort_order: 1, name: "React Native Development", description: "iOS + Android app", quantity: 1, unit_price: 14000, total: 14000 },
      { id: "item-12", proposal_id: "demo-4", sort_order: 2, name: "Backend & API", description: "Node.js API + database", quantity: 1, unit_price: 6000, total: 6000 },
      { id: "item-13", proposal_id: "demo-4", sort_order: 3, name: "QA & App Store", description: "Testing + submission", quantity: 1, unit_price: 2000, total: 2000 },
    ]
  },
  {
    id: "demo-5",
    user_id: "demo",
    public_token: "demo-token-5",
    title: "E-commerce Integration",
    client_name: "RetailPro",
    client_email: "ops@retailpro.com",
    status: "declined",
    cover_tagline: "Sell more with less friction",
    total_amount: 8500,
    currency: "USD",
    view_count: 2,
    first_viewed_at: "2026-03-10T09:00:00Z",
    declined_at: "2026-03-12T11:00:00Z",
    created_at: "2026-03-08T10:00:00Z",
    updated_at: "2026-03-12T11:00:00Z",
    proposal_items: []
  }
]
